image: docker:latest

stages:
  - build
  - push
  - deploy

variables:
  AWS_REGION: "us-east-1"
  ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  ECR_GO_APP: "$ECR_REGISTRY/go-app-repo"
  ECR_NGINX: "$ECR_REGISTRY/nginx-proxy-repo"
  ECS_CLUSTER: "go-app-cluster"
  ECS_SERVICE_GO: "go-app-service"
  ECS_SERVICE_NGINX: "nginx-service"

before_script:
  - apk add --no-cache curl jq aws-cli


build:
  stage: build
  script:
    - docker build -t $ECR_GO_APP:$CI_COMMIT_REF_NAME -f Dockerfile .
    - docker build -t $ECR_NGINX:$CI_COMMIT_REF_NAME -f Dockerfile.nginx .

push:
  stage: push
  script:
    - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
    - docker push $ECR_GO_APP:$CI_COMMIT_REF_NAME
    - docker push $ECR_NGINX:$CI_COMMIT_REF_NAME

deploy:
  stage: deploy
  script:
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE_GO --force-new-deployment
    - aws ecs update-service --cluster $ECS_CLUSTER --service $ECS_SERVICE_NGINX --force-new-deployment
  only:
    - main
