services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    container_name: go-api-container
    restart: always
  proxy:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-proxy
    ports:
      - "80:8080"
    depends_on:
      - api
