services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: go-api
    restart: always

  proxy:
    image: nginx:latest
    container_name: nginx-proxy
    ports:
      - "80:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
